### ISSUE TITLE
interface com.amazonaws.services.dynamodbv2.AmazonDynamoDB is not supported by DynamoDB extension

### ISSUE THREAD

**Issue by rvbabilonia** [madhead/aws-junit5#1]
Hi,

I'm currently upgrading from `dynamodb-v1:1.0.0` to `dynamo-v2:5.0.4`.

Following https://madhead.gitlab.io/aws-junit5/asciidoc/#_basic_usage, I encountered:
```
java.lang.IllegalArgumentException: interface com.amazonaws.services.dynamodbv2.AmazonDynamoDB is not supported by DynamoDB extension.

	at by.dev.madhead.aws_junit5.common.impl.AWSClientExtension.inject(AWSClientExtension.java:31)
	at by.dev.madhead.aws_junit5.common.impl.AWSClientExtension.postProcessTestInstance(AWSClientExtension.java:17)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeTestInstancePostProcessors$5(ClassBasedTestDescriptor.java:337)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.executeAndMaskThrowable(ClassBasedTestDescriptor.java:342)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeTestInstancePostProcessors$6(ClassBasedTestDescriptor.java:337)
```

What am I missing?

Regards,
Rey

**Comment by madhead** [comment]
Hello, Rey!

What a strange class for a v2? AWS Java SDK v2.x uses classes from `software.amazon.awssdk.services.<servicename>` packages

Here is a list of supported v2 clients: https://github.com/madhead/aws-junit5/blob/a72e42d39e615f12f4d02bd92a7e97196cfa5e54/dynamo/v2/src/main/java/by/dev/madhead/aws_junit5/dynamo/v2/DynamoDB.java#L22-L25

Your class seems to be actually v1 client, it is supported via `by.dev.madhead.aws_junit5.dynamo.v1.DynamoDB`: https://github.com/madhead/aws-junit5/blob/a72e42d39e615f12f4d02bd92a7e97196cfa5e54/dynamo/v1/src/main/java/by/dev/madhead/aws_junit5/dynamo/v1/DynamoDB.java#L19-L22

**Comment by rvbabilonia** [comment]
I see! I'm still using `com.amazonaws:aws-java-sdk-dynamodb:1.11.742` instead of `software.amazon.awssdk:dynamodb:2.10.84`. Thanks!
